apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    app: {{ .Chart.Name }}
data:
  glance.yml: |
    server:
      port: 8080

    theme:
      light: false
      background-color: 240 13 14
      primary-color: 43 100 50
      contrast-multiplier: 1.1

    pages:
      - name: Home
        width: slim
        hide-desktop-navigation: true
        columns:
          - size: small
            widgets:
              - type: calendar
                first-day-of-week: monday

              - type: weather
                location: Mumbai, India
                units: metric
                hour-format: 12h

          - size: full
            widgets:
              - type: reddit
                subreddit: technology
                style: vertical-list
                limit: 8
                sort-by: hot
                collapse-after: 4
                show-thumbnails: true
                show-flairs: true

              - type: reddit
                subreddit: selfhosted
                style: vertical-list
                limit: 8
                sort-by: hot
                collapse-after: 4
                show-thumbnails: true
                show-flairs: true
